apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    release: stable #canary
    environment: dev #qa #production
spec:
  ports:
  - port: 80
  selector:
    app: nginx
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      release: stable
      environment: dev
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        release: stable
        environment: dev
    spec:
      containers:
      - name: nginx
        image: registry.gitlab.com/smashingeric/trouxdata.io.iac/nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: "/dev/termination-log"
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
      imagePullSecrets:
      - name: trouxdata-reg-cred
      nodeName: gandalf
      restartPolicy: Always