apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    release: stable #canary
    environment: dev #qa #production
spec:
  ports:
  - port: 80
  selector:
    app: nginx
    tier: frontend